version: "3"

services:
  postgresql:
    image: postgres:13
    container_name: "postgres-for-todo"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    ports:
        - "25432:5432"
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d


volumes:
  database:
    driver: local